name: Build Electron App
on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # This tells GitHub to run on both Windows and Mac simultaneously
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build # Make sure "build" in package.json uses electron-builder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}